install:
	@echo "Install {{cookiecutter.project_name}} ..."
	pip install {{cookiecutter.project_name}}
	

setup:
	@echo "Setup {{cookiecutter.project_name}} ..."
	git init
	git config --local user.email "{{cookiecutter.author_email}}"
	git config --local user.name "{{cookiecutter.author_name}}"	
